apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-bert-pipeline
  template:
    metadata:
      labels:
        app: reddit-bert-pipeline
    specs:
      containers:
        - name: reddit-bert-pipeline-container
          image: 901650294704.dkr.ecr.us-east-1.amazonaws.com/reddit_bert:latest
          command: ["python", "src/reddit_bert/pipeline.py"]
          args: ["${STAGES}"]
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: STAGES
              value: ""    # Default to no stages
