pipeline:
  agent:
    kubernetes:
      label: reddit-bert-pipeline
  parameters:
    - name: RUN_SPLIT_DATA
      type: boolean
      default: true
      description: "Run Split Data Stage"
    - name: RUN_TRAIN
      type: boolean
      default: true
      description: "Run Train Stage"
    - name: RUN_PREDICT
      type: boolean
      default: true
      description: "Run Predict Stage"
  environment:
    STAGES_TO_RUN: ''
  stages:
    - stage: Determine Stages
      steps:
        script:
          stages_to_run = []
          if (params.RUN_SPLIT_DATA) {
            stages_to_run.add("split_data")
          }
          if (params.RUN_TRAIN) {
            stages_to_run.add("train")
          }
          if (params.RUN_PREDICT) {
            stages_to_run.add("predict")
          }
          env.STAGES_TO_RUN = stages_to_run.join(" ")

    - stage: Run Pipeline
      when {
        expression {
          return env.STAGES_TO_RUN != ""
        }
      }
      steps:
        script {
          echo "Running pipeline stages: ${env.STAGES_TO_RUN}"
          sh "kubectl set env deployment/pipeline-deployment STAGES=${env.STAGES_TO_RUN}"
          sh "kubectl rollout restart deployment pipeline-deployment"
        }
