pipeline:
  agent:
    kubernetes:
      label: reddit-bert-pipeline
  parameters:
    - name: RUN_SPLIT_DATA
      type: boolean
      default: true
      description: "Run Split Data Stage"
    - name: RUN_TRAIN
      type: boolean
      default: true
      description: "Run Train Stage"
    - name: RUN_PREDICT
      type: boolean
      default: true
      description: "Run Predict Stage"
  stages:
    - name: Determine Stages
      steps:
        - script: |
            stages_to_run = []
            if RUN_SPLIT_DATA:
              stages_to_run.append("split_data")
            if RUN_TRAIN:
              stages_to_run.append("train")
            if RUN_PREDICT:
              stages_to_run.append("predict")
            env.STAGES_TO_RUN = " ".join(stages_to_run)
    - name: Run Pipeline
      when:
        expression: ${env.STAGES_TO_RUN}
      steps:
        - script: |
            echo "Running pipeline stages: ${env.STAGES_TO_RUN}"
            sh "kubectl set env deployment/pipeline-deployment STAGES=${env.STAGES_TO_RUN}"
            sh "kubectl rollout restart deployment pipeline-deployment"
