DATA:
  raw_data: 's3://fredy-data/reddit/reddit_comment_sample.parquet/'
  training_data: 's3://fredy-data/reddit/reddit_comments_training_data.parquet/'
  test_data: 's3://fredy-data/reddit/reddit_comments_test_data.parquet/'
  predict_output: 's3://fredy-data/reddit/reddit_comments_with_predictions.parquet/'

S3:
  s3_bucket: 'fredy-data'
  model_local_path: 'reddit_model.pt'

MODEL:
  tokenizer_model_str: 'distilbert-base-uncased'
  batch_size: 32
  target_col: 'controversiality'


MLFLOW:
  tracking_uri: "http://localhost:5000"  # Replace with your MLflow server URL
  experiment_name: "Reddit BERT Fine Tuning"